server:
  port: 9000

spring:
  application:
    name: moka-article-service
  datasource:
    url: jdbc:log4jdbc:mysql://${DB_URL}?serverTimezone=Asia/Seoul&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 200
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
        mode: never
logging:
  level:
    com.zaxxer.hikari: warn
    org.hibernate.SQL: warn